// driving_test_top.v — Top-level wiring for GEL372 FPGA Driving Test.
//
// Target: Altera DE2 — EP2C35F672C6
// Tool:   Intel Quartus Prime (see driving_test.qsf for pin assignments)
//
// Reset strategy: KEY[3] is the start/reset button (active-low on DE2).
//   rst_n = KEY[3] — held low at power-up releases all registers.
//
// 60 Hz game tick: derived from vsync falling edge (end of each frame).
// VGA pixel clock: 25 MHz, generated by halving the 50 MHz system clock.

`include "track_data.vh"

module driving_test_top (
    input  wire        CLOCK_50,
    input  wire [3:0]  KEY,        // active-low push buttons
    input  wire [1:0]  SW,         // SW[0]=accel, SW[1]=brake
    // VGA
    output wire [9:0]  VGA_R,
    output wire [9:0]  VGA_G,
    output wire [9:0]  VGA_B,
    output wire        VGA_HS,
    output wire        VGA_VS,
    output wire        VGA_BLANK,
    output wire        VGA_SYNC,
    output wire        VGA_CLK,
    // LCD
    output wire        LCD_EN,
    output wire        LCD_RS,
    output wire        LCD_RW,
    output wire [7:4]  LCD_DATA,
    // Seven-segment
    output wire [6:0]  HEX0, HEX1, HEX2, HEX3, HEX4, HEX5,
    // LEDs
    output wire [17:0] LEDR,
    output wire [7:0]  LEDG,
    // Audio buzzer (connect to GPIO_0[0])
    output wire        GPIO_0_0
);

// ── Reset: KEY[3] active-low → rst_n ──────────────────────────────────────
wire rst_n = KEY[3];

// ─────────────────────────────────────────────────────────────────────────
//  VGA controller
// ─────────────────────────────────────────────────────────────────────────
wire        pclk, active, hsync, vsync;
wire [9:0]  px, py;

vga_controller u_vga (
    .clk50  (CLOCK_50), .rst_n (rst_n),
    .hsync  (hsync),    .vsync (vsync),
    .px     (px),       .py    (py),
    .active (active),   .pclk  (pclk)
);

assign VGA_HS    = hsync;
assign VGA_VS    = vsync;
assign VGA_SYNC  = 1'b0;
assign VGA_BLANK = active;
assign VGA_CLK   = pclk;

// ─────────────────────────────────────────────────────────────────────────
//  60 Hz game tick: falling edge of vsync
// ─────────────────────────────────────────────────────────────────────────
reg vsync_d;
always @(posedge CLOCK_50) begin
    if (!rst_n) vsync_d <= 1'b1;
    else        vsync_d <= vsync;
end
wire tick_60hz = vsync_d & ~vsync;

// ─────────────────────────────────────────────────────────────────────────
//  Input handler
// ─────────────────────────────────────────────────────────────────────────
wire accel, brake, steer_left, steer_right, start_btn_db;

input_handler u_input (
    .clk50       (CLOCK_50), .rst_n (rst_n),
    .sw          (SW[1:0]),  .key   (KEY),
    .accel       (accel),    .brake (brake),
    .steer_left  (steer_left), .steer_right (steer_right),
    .start_btn   (start_btn_db)
);

// KEY[3] serves as reset, so generate the start pulse from its release edge.
// This keeps reset active while pressed, but still lets the game leave IDLE.
reg key3_prev;
always @(posedge CLOCK_50) begin
    if (!rst_n)
        key3_prev <= 1'b0;
    else
        key3_prev <= KEY[3];
end

wire start_btn = KEY[3] & ~key3_prev;

// ─────────────────────────────────────────────────────────────────────────
//  Car controller
// ─────────────────────────────────────────────────────────────────────────
wire [9:0]   car_x, car_y;
wire [2:0]   car_angle;
wire [8:0]   heading_deg;
wire [7:0]   speed_kph;
wire [111:0] car_row_bus;  // 8 rows × 14 bits packed
wire         game_active;

car_controller u_car (
    .clk50       (CLOCK_50),    .rst_n      (rst_n),
    .tick_60hz   (tick_60hz),
    .accel       (accel),       .brake       (brake),
    .steer_left  (steer_left),  .steer_right (steer_right),
    .game_active (game_active),
    .car_x       (car_x),       .car_y       (car_y),
    .car_angle   (car_angle),   .heading_deg (heading_deg),
    .speed_kph   (speed_kph),
    .car_row_bus (car_row_bus)
);

// ─────────────────────────────────────────────────────────────────────────
//  Collision detection — corner off-road checks
// ─────────────────────────────────────────────────────────────────────────
wire [3:0] corner_offroad;

// Four corner probes: TL(-4,-7), TR(+3,-7), BL(-4,+6), BR(+3,+6)
corner_probe u_c0 (.px(car_x - 10'd4), .py(car_y - 10'd7), .offroad(corner_offroad[0]));
corner_probe u_c1 (.px(car_x + 10'd3), .py(car_y - 10'd7), .offroad(corner_offroad[1]));
corner_probe u_c2 (.px(car_x - 10'd4), .py(car_y + 10'd6), .offroad(corner_offroad[2]));
corner_probe u_c3 (.px(car_x + 10'd3), .py(car_y + 10'd6), .offroad(corner_offroad[3]));

wire collision;

collision_detector u_col (
    .clk50          (CLOCK_50), .rst_n (rst_n),
    .tick_60hz      (tick_60hz),
    .car_x          (car_x),    .car_y (car_y),
    .corner_offroad (corner_offroad),
    .collision      (collision)
);

// ─────────────────────────────────────────────────────────────────────────
//  Game FSM
// ─────────────────────────────────────────────────────────────────────────
wire [1:0]  game_state;
wire [15:0] remaining_sec;
wire [7:0]  remaining_ms;

fsm_game u_fsm (
    .clk50       (CLOCK_50),    .rst_n      (rst_n),
    .tick_60hz   (tick_60hz),
    .start_btn   (start_btn),   .collision  (collision),
    .car_x       (car_x),       .car_y      (car_y),
    .car_angle   (car_angle),
    .game_state  (game_state),  .game_active(game_active),
    .remaining_sec (remaining_sec), .remaining_ms (remaining_ms)
);

// ─────────────────────────────────────────────────────────────────────────
//  Track renderer
// ─────────────────────────────────────────────────────────────────────────
wire [23:0] rgb;

track_renderer u_render (
    .pclk        (pclk),      .rst_n   (rst_n),
    .active      (active),
    .px          (px),        .py      (py),
    .car_x       (car_x),     .car_y   (car_y),
    .car_angle   (car_angle), .heading_deg (heading_deg), .car_row_bus (car_row_bus),
    .rgb         (rgb)
);

// DE2 VGA DAC is 10-bit; drive MSBs with our 8-bit color (LSBs = 0)
assign VGA_R = {rgb[23:16], 2'b00};
assign VGA_G = {rgb[15:8],  2'b00};
assign VGA_B = {rgb[7:0],   2'b00};

// ─────────────────────────────────────────────────────────────────────────
//  LCD controller
// ─────────────────────────────────────────────────────────────────────────
lcd_controller u_lcd (
    .clk50      (CLOCK_50),  .rst_n     (rst_n),
    .game_state (game_state),
    .LCD_EN     (LCD_EN),    .LCD_RS    (LCD_RS),
    .LCD_RW     (LCD_RW),    .LCD_DATA  (LCD_DATA)
);

// ─────────────────────────────────────────────────────────────────────────
//  Seven-segment display
// ─────────────────────────────────────────────────────────────────────────
seg7_display u_seg7 (
    .clk50       (CLOCK_50),    .rst_n      (rst_n),
    .remaining_sec (remaining_sec), .remaining_ms (remaining_ms),
    .speed_kph   (speed_kph),
    .HEX0(HEX0), .HEX1(HEX1), .HEX2(HEX2),
    .HEX3(HEX3), .HEX4(HEX4), .HEX5(HEX5)
);

// ─────────────────────────────────────────────────────────────────────────
//  LED indicator
// ─────────────────────────────────────────────────────────────────────────
led_indicator u_leds (
    .clk50      (CLOCK_50), .rst_n     (rst_n),
    .game_state (game_state),
    .LEDR       (LEDR),     .LEDG      (LEDG)
);

// ─────────────────────────────────────────────────────────────────────────
//  Audio controller
// ─────────────────────────────────────────────────────────────────────────
audio_controller u_audio (
    .clk50      (CLOCK_50), .rst_n     (rst_n),
    .game_state (game_state),
    .buzzer_out (GPIO_0_0)
);

endmodule

// ─────────────────────────────────────────────────────────────────────────
//  corner_probe — Combinational is_on_track test for a single pixel.
//  Returns offroad=1 when the pixel is in the green off-road zone.
// ─────────────────────────────────────────────────────────────────────────
`include "track_data.vh"

module corner_probe (
    input  wire [9:0] px,
    input  wire [9:0] py,
    output wire       offroad
);

function [0:0] is_on_track_cp;
    input [9:0] fpx, fpy;
    reg signed [20:0] cross2, cross3, cross4;
    reg in_inner;
    begin
        is_on_track_cp = 1'b0;

        if (fpx < `OUTER_LEFT  || fpx > `OUTER_RIGHT ||
            fpy < `OUTER_TOP   || fpy > `OUTER_BOTTOM) begin
            is_on_track_cp = 1'b0;

        end else if (fpx > `TR_CORNER_X && fpy < `TR_CORNER_Y) begin
            if (($unsigned(fpx)-10'd590)*10'd38 <= (10'd58-$unsigned(fpy))*10'd30)
                is_on_track_cp = 1'b1;

        end else if (fpx > `BR_CORNER_X && fpy > `BR_CORNER_Y) begin
            if (($unsigned(fpx)-10'd581)*10'd30 >= ($unsigned(fpy)-10'd350)*10'd39)
                is_on_track_cp = 1'b1;

        end else begin
            in_inner = 1'b0;

            if (fpy >= `INNER_TL_Y && fpx >= `INNER_TL_X1 && fpx <= `ISLAND_TOP_X1) begin
                cross2 = -21'sd103 * $signed({1'b0,fpy} - 10'd91)
                         - 21'sd87  * $signed({1'b0,fpx} - 10'd186);
                cross3 = 21'sd34 * $signed({1'b0,fpy} - 10'd178)
                         - 21'sd41 * $signed({1'b0,fpx} - 10'd83);
                cross4 = 21'sd157 * $signed({1'b0,fpy} - 10'd219)
                         + 21'sd128 * $signed({1'b0,fpx} - 10'd117);
                if (fpy <= `E2_Y2) begin
                    if (cross2 < 21'sd0) begin
                        in_inner = 1'b1;
                    end
                end

                if (!in_inner && fpy <= `E3_Y2) begin
                    if (cross3 < 21'sd0 && cross4 < 21'sd0) begin
                        in_inner = 1'b1;
                    end
                end
            end

            if (fpx >= `ISLAND_BX1 && fpx <= `ISLAND_BX2 &&
                fpy >= `ISLAND_BY1 && fpy <= `ISLAND_BY2) begin
                if (!(fpx >= `STEP_CUTOUT_X1 && fpx <= `STEP_CUTOUT_X2 &&
                      fpy >= `STEP_CUTOUT_Y1 && fpy <= `STEP_CUTOUT_Y2)) begin
                    if (fpx >= `STEP_LR_X1 && fpx <= `STEP_LR_X2 &&
                        fpy >= `STEP_LR_Y1 && fpy <= `STEP_LR_Y2) begin
                        in_inner = 1'b1;
                    end else if (fpx >= `ISLAND_LEFT_X && fpy >= `ISLAND_LEFT_Y1) begin
                        in_inner = 1'b1;
                    end else if (fpx < `ISLAND_LEFT_X && fpy < `ISLAND_LEFT_Y1) begin
                        in_inner = 1'b1;
                    end
                end
            end

            if (fpx >= `BOT_LEFT_X1 && fpx <= `BOT_LEFT_X2 &&
                fpy >= `BOT_LEFT_Y1 && fpy <= `BOT_LEFT_Y2) in_inner = 1'b1;

            if (fpx >= `BOT_LEFT_X2 && fpx <= `BOT_EXT_X1 &&
                fpy >= `BOT_INNER_Y && fpy <= `ISLAND_BY2)  in_inner = 1'b1;

            if (fpx >= `BOT_EXT_X1 && fpx <= `BOT_EXT_X2 &&
                fpy >= `BOT_EXT_Y1 && fpy <= `BOT_EXT_Y2)  in_inner = 1'b1;

            is_on_track_cp = ~in_inner;
        end
    end
endfunction

assign offroad = ~is_on_track_cp(px, py);

endmodule
