// driving_test_top.v — Top-level wiring for GEL372 FPGA Driving Test.
//
// Target: Altera DE2 — EP2C35F672C6
// Tool:   Intel Quartus Prime (see driving_test.qsf for pin assignments)
//
// Reset strategy: KEY[3] is the start/reset button (active-low on DE2).
//   rst_n = KEY[3] — held low at power-up releases all registers.
//
// 60 Hz game tick: derived from vsync falling edge (end of each frame).
// VGA pixel clock: 25 MHz, generated by halving the 50 MHz system clock.
//
// Procedural track: track_gen samples a free-running LFSR on reset release
// to pick one of four rectangular-segment track layouts.

`include "track_data.vh"

module driving_test_top (
    input  wire        CLOCK_50,
    input  wire [3:0]  KEY,        // active-low push buttons
    input  wire [1:0]  SW,         // SW[0]=accel, SW[1]=brake
    // VGA
    output wire [9:0]  VGA_R,
    output wire [9:0]  VGA_G,
    output wire [9:0]  VGA_B,
    output wire        VGA_HS,
    output wire        VGA_VS,
    output wire        VGA_BLANK,
    output wire        VGA_SYNC,
    output wire        VGA_CLK,
    // LCD
    output wire        LCD_EN,
    output wire        LCD_RS,
    output wire        LCD_RW,
    output wire [7:4]  LCD_DATA,
    // Seven-segment
    output wire [6:0]  HEX0, HEX1, HEX2, HEX3, HEX4, HEX5,
    // LEDs
    output wire [17:0] LEDR,
    output wire [7:0]  LEDG,
    // Audio buzzer (connect to GPIO_0[0])
    output wire        GPIO_0_0
);

// ── Reset: KEY[3] active-low → rst_n ──────────────────────────────────────
wire rst_n = KEY[3];

// ─────────────────────────────────────────────────────────────────────────
//  VGA controller
// ─────────────────────────────────────────────────────────────────────────
wire        pclk, active, hsync, vsync;
wire [9:0]  px, py;

vga_controller u_vga (
    .clk50  (CLOCK_50), .rst_n (rst_n),
    .hsync  (hsync),    .vsync (vsync),
    .px     (px),       .py    (py),
    .active (active),   .pclk  (pclk)
);

assign VGA_HS    = hsync;
assign VGA_VS    = vsync;
assign VGA_SYNC  = 1'b0;
assign VGA_BLANK = active;
assign VGA_CLK   = pclk;

// ─────────────────────────────────────────────────────────────────────────
//  60 Hz game tick: falling edge of vsync
// ─────────────────────────────────────────────────────────────────────────
reg vsync_d;
always @(posedge CLOCK_50) begin
    if (!rst_n) vsync_d <= 1'b1;
    else        vsync_d <= vsync;
end
wire tick_60hz = vsync_d & ~vsync;

// ─────────────────────────────────────────────────────────────────────────
//  Input handler
// ─────────────────────────────────────────────────────────────────────────
wire accel, brake, steer_left, steer_right, start_btn_db;

input_handler u_input (
    .clk50       (CLOCK_50), .rst_n (rst_n),
    .sw          (SW[1:0]),  .key   (KEY),
    .accel       (accel),    .brake (brake),
    .steer_left  (steer_left), .steer_right (steer_right),
    .start_btn   (start_btn_db)
);

reg key3_prev;
always @(posedge CLOCK_50) begin
    if (!rst_n) key3_prev <= 1'b0;
    else        key3_prev <= KEY[3];
end
wire start_btn = KEY[3] & ~key3_prev;

// ─────────────────────────────────────────────────────────────────────────
//  Procedural track generator
// ─────────────────────────────────────────────────────────────────────────
wire [(`MAX_SEGS *40)-1:0]  seg_bus;
wire [3:0]                  num_segs;
wire [(`MAX_CONES*20)-1:0]  cone_bus;
wire [3:0]                  num_cones;
wire [(`MAX_BLDGS*36)-1:0]  bldg_bus;
wire [3:0]                  num_bldgs;

track_gen u_tgen (
    .clk50     (CLOCK_50), .rst_n    (rst_n),
    .seg_bus   (seg_bus),  .num_segs (num_segs),
    .cone_bus  (cone_bus), .num_cones(num_cones),
    .bldg_bus  (bldg_bus), .num_bldgs(num_bldgs)
);

// ─────────────────────────────────────────────────────────────────────────
//  Car controller
// ─────────────────────────────────────────────────────────────────────────
wire [9:0]   car_x, car_y;
wire [2:0]   car_angle;
wire [8:0]   heading_deg;
wire [7:0]   speed_kph;
wire [307:0] car_row_bus;
wire         game_active;

car_controller u_car (
    .clk50       (CLOCK_50),    .rst_n      (rst_n),
    .tick_60hz   (tick_60hz),
    .accel       (accel),       .brake       (brake),
    .steer_left  (steer_left),  .steer_right (steer_right),
    .game_active (game_active),
    .car_x       (car_x),       .car_y       (car_y),
    .car_angle   (car_angle),   .heading_deg (heading_deg),
    .speed_kph   (speed_kph),
    .car_row_bus (car_row_bus)
);

// ─────────────────────────────────────────────────────────────────────────
//  Collision detection — corner off-road probes + cone check
// ─────────────────────────────────────────────────────────────────────────
wire [3:0] corner_offroad;

// Four corner probes: TL(-5,-7), TR(+4,-7), BL(-5,+6), BR(+4,+6)
corner_probe u_c0 (.px(car_x - 10'd5), .py(car_y - 10'd7),
                   .seg_bus(seg_bus), .num_segs(num_segs),
                   .offroad(corner_offroad[0]));
corner_probe u_c1 (.px(car_x + 10'd4), .py(car_y - 10'd7),
                   .seg_bus(seg_bus), .num_segs(num_segs),
                   .offroad(corner_offroad[1]));
corner_probe u_c2 (.px(car_x - 10'd5), .py(car_y + 10'd6),
                   .seg_bus(seg_bus), .num_segs(num_segs),
                   .offroad(corner_offroad[2]));
corner_probe u_c3 (.px(car_x + 10'd4), .py(car_y + 10'd6),
                   .seg_bus(seg_bus), .num_segs(num_segs),
                   .offroad(corner_offroad[3]));

wire collision;

collision_detector u_col (
    .clk50          (CLOCK_50), .rst_n     (rst_n),
    .tick_60hz      (tick_60hz),
    .car_x          (car_x),    .car_y     (car_y),
    .corner_offroad (corner_offroad),
    .cone_bus       (cone_bus), .num_cones (num_cones),
    .collision      (collision)
);

// ─────────────────────────────────────────────────────────────────────────
//  Game FSM
// ─────────────────────────────────────────────────────────────────────────
wire [1:0]  game_state;
wire [15:0] remaining_sec;
wire [7:0]  remaining_ms;

fsm_game u_fsm (
    .clk50       (CLOCK_50),    .rst_n      (rst_n),
    .tick_60hz   (tick_60hz),
    .start_btn   (start_btn),   .collision  (collision),
    .car_x       (car_x),       .car_y      (car_y),
    .car_angle   (car_angle),
    .game_state  (game_state),  .game_active(game_active),
    .remaining_sec (remaining_sec), .remaining_ms (remaining_ms)
);

// ─────────────────────────────────────────────────────────────────────────
//  Track renderer
// ─────────────────────────────────────────────────────────────────────────
wire [23:0] rgb;

track_renderer u_render (
    .pclk        (pclk),       .rst_n      (rst_n),
    .active      (active),
    .px          (px),         .py         (py),
    .car_x       (car_x),      .car_y      (car_y),
    .car_angle   (car_angle),  .heading_deg(heading_deg),
    .car_row_bus (car_row_bus),
    .seg_bus     (seg_bus),    .num_segs   (num_segs),
    .cone_bus    (cone_bus),   .num_cones  (num_cones),
    .bldg_bus    (bldg_bus),   .num_bldgs  (num_bldgs),
    .rgb         (rgb)
);

assign VGA_R = {rgb[23:16], 2'b00};
assign VGA_G = {rgb[15:8],  2'b00};
assign VGA_B = {rgb[7:0],   2'b00};

// ─────────────────────────────────────────────────────────────────────────
//  LCD / 7-seg / LEDs / Audio (unchanged)
// ─────────────────────────────────────────────────────────────────────────
lcd_controller u_lcd (
    .clk50      (CLOCK_50),  .rst_n     (rst_n),
    .game_state (game_state),
    .LCD_EN     (LCD_EN),    .LCD_RS    (LCD_RS),
    .LCD_RW     (LCD_RW),    .LCD_DATA  (LCD_DATA)
);

seg7_display u_seg7 (
    .clk50       (CLOCK_50),       .rst_n        (rst_n),
    .remaining_sec(remaining_sec), .remaining_ms (remaining_ms),
    .speed_kph   (speed_kph),
    .HEX0(HEX0), .HEX1(HEX1), .HEX2(HEX2),
    .HEX3(HEX3), .HEX4(HEX4), .HEX5(HEX5)
);

led_indicator u_leds (
    .clk50      (CLOCK_50), .rst_n     (rst_n),
    .game_state (game_state),
    .LEDR       (LEDR),     .LEDG      (LEDG)
);

audio_controller u_audio (
    .clk50      (CLOCK_50), .rst_n     (rst_n),
    .game_state (game_state),
    .buzzer_out (GPIO_0_0)
);

endmodule

// ─────────────────────────────────────────────────────────────────────────
//  corner_probe — Combinational off-road test using seg_bus rectangles.
//  Returns offroad=1 when pixel is NOT inside any road segment.
// ─────────────────────────────────────────────────────────────────────────
`include "track_data.vh"

module corner_probe (
    input  wire [9:0] px,
    input  wire [9:0] py,
    input  wire [(`MAX_SEGS*40)-1:0] seg_bus,
    input  wire [3:0]                num_segs,
    output wire       offroad
);

function [0:0] is_on_track_cp;
    input [9:0] fpx, fpy;
    input [(`MAX_SEGS*40)-1:0] sbus;
    input [3:0] nseg;
    integer i;
    reg [9:0] sx1, sy1, sx2, sy2;
    begin
        is_on_track_cp = 1'b0;
        for (i = 0; i < `MAX_SEGS; i = i + 1) begin
            if (i < nseg) begin
                sx1 = sbus[i*40+39 -: 10];
                sy1 = sbus[i*40+29 -: 10];
                sx2 = sbus[i*40+19 -: 10];
                sy2 = sbus[i*40+ 9 -: 10];
                if (fpx >= sx1 && fpx <= sx2 && fpy >= sy1 && fpy <= sy2)
                    is_on_track_cp = 1'b1;
            end
        end
    end
endfunction

assign offroad = ~is_on_track_cp(px, py, seg_bus, num_segs);

endmodule